<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'DirkGroenen\\Pinterest\\' => array($vendorDir . '/dirkgroenen/pinterest-api-php/src/Pinterest'),
);
