<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit92d6c563fd359713864f8c4c60fb7ec3
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DirkGroenen\\Pinterest\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DirkGroenen\\Pinterest\\' => 
        array (
            0 => __DIR__ . '/..' . '/dirkgroenen/pinterest-api-php/src/Pinterest',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit92d6c563fd359713864f8c4c60fb7ec3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit92d6c563fd359713864f8c4c60fb7ec3::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
