filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=.coverage-report.xml'
                coverage:
                    file: '.coverage-report.xml'
                    format: 'php-clover'